package generator

import (
	"fmt"
	"strings"

	"dhcp-ui/internal/models"
)

// GenerateDHCPConfig converts data models into ISC dhcpd.conf configuration syntax
// role: "primary" or "secondary"
func GenerateDHCPConfig(
	role string,
	primaryNode models.Node,
	secondaryNode models.Node,
	global models.GlobalSettings,
	subnets []models.Subnet,
	staticLeases []models.StaticLease,
) string {
	var sb strings.Builder

	sb.WriteString("# ====================================================================\n")
	sb.WriteString(fmt.Sprintf("# Auto-generated by DHCP-UI Web Management (Role: %s)\n", strings.ToUpper(role)))
	sb.WriteString("# DO NOT EDIT THIS FILE MANUALLY - CHANGES WILL BE OVERWRITTEN\n")
	sb.WriteString("# ====================================================================\n\n")

	// Global Directives
	if global.Authoritative {
		sb.WriteString("authoritative;\n")
	}
	if global.DefaultLeaseTime > 0 {
		sb.WriteString(fmt.Sprintf("default-lease-time %d;\n", global.DefaultLeaseTime))
	}
	if global.MaxLeaseTime > 0 {
		sb.WriteString(fmt.Sprintf("max-lease-time %d;\n", global.MaxLeaseTime))
	}
	if global.DomainName != "" {
		sb.WriteString(fmt.Sprintf("option domain-name \"%s\";\n", global.DomainName))
	}
	if global.DNSServers != "" {
		sb.WriteString(fmt.Sprintf("option domain-name-servers %s;\n", global.DNSServers))
	}
	if global.CustomOptions != "" {
		sb.WriteString("\n# Custom Global Options\n")
		sb.WriteString(global.CustomOptions)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")

	// Failover Peer Block (RFC 3074) - ISC DHCP requires at least 1 referring pool
	failoverPoolCount := 0
	for _, sn := range subnets {
		if sn.EnableFailover {
			failoverPoolCount += len(sn.Pools)
		}
	}
	hasFailover := primaryNode.DHCPIP != "" && secondaryNode.DHCPIP != "" && failoverPoolCount > 0
	if hasFailover {
		sb.WriteString("# --------------------------------------------------------------------\n")
		sb.WriteString("# DHCP Failover Configuration\n")
		sb.WriteString("# --------------------------------------------------------------------\n")
		sb.WriteString("failover peer \"dhcp-failover\" {\n")
		if role == "primary" {
			sb.WriteString("  primary;\n")
			sb.WriteString(fmt.Sprintf("  address %s;\n", primaryNode.DHCPIP))
			sb.WriteString("  port 647;\n")
			sb.WriteString(fmt.Sprintf("  peer address %s;\n", secondaryNode.DHCPIP))
			sb.WriteString("  peer port 647;\n")
			sb.WriteString("  max-response-delay 60;\n")
			sb.WriteString("  max-unacked-updates 10;\n")
			sb.WriteString("  mclt 3600;\n")
			sb.WriteString("  split 128;\n")
			sb.WriteString("  load balance max seconds 3;\n")
		} else {
			sb.WriteString("  secondary;\n")
			sb.WriteString(fmt.Sprintf("  address %s;\n", secondaryNode.DHCPIP))
			sb.WriteString("  port 647;\n")
			sb.WriteString(fmt.Sprintf("  peer address %s;\n", primaryNode.DHCPIP))
			sb.WriteString("  peer port 647;\n")
			sb.WriteString("  max-response-delay 60;\n")
			sb.WriteString("  max-unacked-updates 10;\n")
			sb.WriteString("  load balance max seconds 3;\n")
		}
		sb.WriteString("}\n\n")
	}

	// Subnet & Pool Blocks (RFC 2132 Scope Options)
	sb.WriteString("# --------------------------------------------------------------------\n")
	sb.WriteString("# Subnet and Dynamic Pool Declarations\n")
	sb.WriteString("# --------------------------------------------------------------------\n")
	for _, sn := range subnets {
		cleanNet := strings.TrimSpace(strings.Split(sn.NetworkAddress, "/")[0])
		netmask := strings.TrimSpace(sn.Netmask)
		if netmask == "" {
			netmask = "255.255.255.0"
		}
		sb.WriteString(fmt.Sprintf("# Subnet: %s (%s)\n", cleanNet, sn.Description))
		sb.WriteString(fmt.Sprintf("subnet %s netmask %s {\n", cleanNet, netmask))
		if sn.Gateway != "" {
			sb.WriteString(fmt.Sprintf("  option routers %s;\n", sn.Gateway))
		}
		if sn.Netmask != "" {
			sb.WriteString(fmt.Sprintf("  option subnet-mask %s;\n", sn.Netmask))
		}
		if sn.DNSServers != "" {
			sb.WriteString(fmt.Sprintf("  option domain-name-servers %s;\n", sn.DNSServers))
		}
		if sn.DomainName != "" {
			sb.WriteString(fmt.Sprintf("  option domain-name \"%s\";\n", sn.DomainName))
		}
		if sn.NTPServers != "" {
			sb.WriteString(fmt.Sprintf("  option ntp-servers %s;\n", sn.NTPServers))
		}
		if sn.TFTPServer != "" {
			sb.WriteString(fmt.Sprintf("  next-server %s;\n", sn.TFTPServer))
		}
		if sn.BootFileName != "" {
			sb.WriteString(fmt.Sprintf("  filename \"%s\";\n", sn.BootFileName))
		}

		leaseSec := sn.LeaseTime
		if sn.LeaseDays > 0 || sn.LeaseHours > 0 || sn.LeaseMinutes > 0 {
			leaseSec = (sn.LeaseDays * 86400) + (sn.LeaseHours * 3600) + (sn.LeaseMinutes * 60)
		}
		if leaseSec > 0 {
			sb.WriteString(fmt.Sprintf("  default-lease-time %d;\n", leaseSec))
			sb.WriteString(fmt.Sprintf("  max-lease-time %d;\n", leaseSec*2))
		}

		if sn.CustomOptions != "" {
			sb.WriteString(fmt.Sprintf("  # Custom Scope Options\n  %s\n", strings.ReplaceAll(sn.CustomOptions, "\n", "\n  ")))
		}

		// Pools in this Subnet
		for _, pool := range sn.Pools {
			sb.WriteString("  pool {\n")
			if sn.EnableFailover && hasFailover {
				peerName := pool.FailoverPeerName
				if peerName == "" {
					peerName = "dhcp-failover"
				}
				sb.WriteString(fmt.Sprintf("    failover peer \"%s\";\n", peerName))
			}
			if pool.DenyUnknownClients {
				sb.WriteString("    deny unknown-clients;\n")
			}
			sb.WriteString(fmt.Sprintf("    range %s %s;\n", pool.RangeStart, pool.RangeEnd))
			sb.WriteString("  }\n")
		}

		sb.WriteString("}\n\n")
	}

	// Static Hosts (MAC Reservations)
	if len(staticLeases) > 0 {
		sb.WriteString("# --------------------------------------------------------------------\n")
		sb.WriteString("# Static IP Reservations (Host Declarations)\n")
		sb.WriteString("# --------------------------------------------------------------------\n")
		for _, host := range staticLeases {
			safeHostname := sanitizeHostname(host.Hostname)
			sb.WriteString(fmt.Sprintf("host %s {\n", safeHostname))
			sb.WriteString(fmt.Sprintf("  hardware ethernet %s;\n", strings.ToLower(host.MACAddress)))
			sb.WriteString(fmt.Sprintf("  fixed-address %s;\n", host.IPAddress))
			if host.Description != "" {
				sb.WriteString(fmt.Sprintf("  # Description: %s\n", host.Description))
			}
			sb.WriteString("}\n\n")
		}
	}

	return sb.String()
}

func sanitizeHostname(name string) string {
	name = strings.TrimSpace(name)
	name = strings.ReplaceAll(name, " ", "-")
	name = strings.ReplaceAll(name, "_", "-")
	if name == "" {
		return "client"
	}
	return name
}
